/*
 * generated by Xtext 2.9.1
 */
package de.malime.xtext.webdsl.tests

import com.google.inject.Inject
import de.malime.xtext.webdsl.webDsl.Web
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(WebDslInjectorProvider)
class WebDslParsingTest{

	@Inject
	ParseHelper<Web> parseHelper;
	@Test 
	def void loadModel() {
		val result = parseHelper.parse('''
theme "theme/malime.css"
meta keywords = "keywords"
meta description = "description"
menu "Index" ( "index.html" )
    meta keywords = "keywords"
    meta description = "description"
menu "Menu1" ( "menu1.html" )  
    submenu "Submenu1.1" ( "menu1/submenu1.html" ) 
    submenu "Submenu1.2" ( "menu1/submenu2.html" )
		subsubmenu "Subsubmenu1.2.1" ( "menu1/submenu2/subsubmenu1.html" )
		subsubmenu "Subsubmenu1.2.2" ( "menu1/submenu2/subsubmenu2.html" )
		subsubmenu "Subsubmenu1.2.3" ( "menu1/submenu2/subsubmenu3.html" )		
		subsubmenu "Subsubmenu1.2.4" ( "menu1/submenu2/subsubmenu4.html" )
menu "Menu2" ( "menu2.html" )  
    submenu "Submenu2.1" ( "menu2/submenu1.html" ) 
    submenu "Submenu2.2" ( "menu2/submenu2.html" )
		subsubmenu "Subsubmenu2.2.1" ( "menu2/submenu2/subsubmenu1.html" )    		''')
		Assert.assertNotNull(result)
	}

}
